//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateMe.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DateMe.lang.pl", typeof(pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatujJe!.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wybierz folder.
        /// </summary>
        internal static string choose_folder_button {
            get {
                return ResourceManager.GetString("choose_folder_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz folder ze zdjeciami.
        /// </summary>
        internal static string chosen_folder_label {
            get {
                return ResourceManager.GetString("chosen_folder_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odatowanych zdjęć: .
        /// </summary>
        internal static string confirmation_text_1 {
            get {
                return ResourceManager.GetString("confirmation_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Niemożliwych do odatowania: .
        /// </summary>
        internal static string confirmation_text_2 {
            get {
                return ResourceManager.GetString("confirmation_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datowanie zakończone.
        /// </summary>
        internal static string confirmation_title {
            get {
                return ResourceManager.GetString("confirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datuj je!.
        /// </summary>
        internal static string print_dates_button {
            get {
                return ResourceManager.GetString("print_dates_button", resourceCulture);
            }
        }
    }
}
